### ISSUE TITLE
crash in callback

### ISSUE THREAD

**Issue by bububa** [Mark-Ma-1988/PhotoSolution#1]
class Photo->getOriginalImage->callback(originalImage!)

**Comment by Mark-Ma-1988** [comment]
Hi @bububa I could not replicate it, could you tell me some detail? which version of this library, which device you are using? which language you are using(Swift or Objective-C)?

**Comment by bawangshenqiang** [comment]
对，就是在那崩了，1.0.2，7p，oc

**Comment by bawangshenqiang** [comment]
相册选择图片的时候只能点击右上角的小圆圈吗？点不准就崩了

**Comment by bawangshenqiang** [comment]
不能点击图片放大，一点图片就崩

**Comment by bawangshenqiang** [comment]
模拟器测试没问题，选择图片的时候单击放大，7Plus测试的时候，选择图片单击不放大，是选中，有时候还崩func getOriginalImage(callback: @escaping (UIImage) -> Void) {
        let manager = PHImageManager.default()
        let option = PHImageRequestOptions()
        option.isSynchronous = true
        manager.requestImage(for: asset, targetSize:PHImageManagerMaximumSize, contentMode: .aspectFit, options: option) { (originImage, info) in
            callback(originImage!)
        }
    }

**Comment by Mark-Ma-1988** [comment]
我的微信号：qq771710136。加一下吧

**Comment by Mark-Ma-1988** [comment]
Fixed, I close this issue now.
